# Generated by Django 4.0.4 on 2022-05-13 18:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='URL')),
                ('raw_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Raw page content')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Page content')),
                ('meta_title', models.CharField(default='', max_length=510, verbose_name='Meta title')),
                ('meta_description', models.CharField(default='', max_length=510, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(default='', max_length=255, verbose_name='Meta keywords')),
                ('canonical', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Canonical url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Page content',
                'verbose_name_plural': 'Page content',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_page.pagecontent', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Words',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('url', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_page.pagecontent', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Additional links',
                'verbose_name_plural': 'Additional links',
            },
        ),
    ]
