# Generated by Django 4.0.4 on 2022-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='url',
            field=models.TextField(db_index=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='word',
            name='value',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Value'),
        ),
    ]
