# Generated by Django 4.0.4 on 2022-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[['crawler', 'Crawler process'], ['text_indexing', 'Text indexing process']], max_length=255, verbose_name='Type')),
                ('text', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Logs',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
