# Generated by Django 4.0.4 on 2022-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[['crawler', 'Crawler process'], ['text_indexing', 'Text indexing process']], default='crawler', max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
